//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Building_Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC_Building_Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASRock_AMD_Radeon_RX_6600_Challenger_D_8GB {
            get {
                object obj = ResourceManager.GetObject("ASRock_AMD_Radeon_RX_6600_Challenger_D_8GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Asus_ROG_Strix_GeForce_GTX_1060 {
            get {
                object obj = ResourceManager.GetObject("Asus_ROG_Strix_GeForce_GTX_1060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_TUF_Gaming_RX_7800_XT {
            get {
                object obj = ResourceManager.GetObject("ASUS_TUF_Gaming_RX_7800_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_ASUS_ROG_Strix_Helios {
            get {
                object obj = ResourceManager.GetObject("case_ASUS_ROG_Strix_Helios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_be_quiet__Pure_Base_500DX {
            get {
                object obj = ResourceManager.GetObject("case_be_quiet__Pure_Base_500DX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_be_quiet__Silent_Base_802 {
            get {
                object obj = ResourceManager.GetObject("case_be_quiet__Silent_Base_802", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Cooler_Master_MasterBox_NR200P {
            get {
                object obj = ResourceManager.GetObject("case_Cooler_Master_MasterBox_NR200P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Cooler_Master_MasterCase_H500M {
            get {
                object obj = ResourceManager.GetObject("case_Cooler_Master_MasterCase_H500M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Corsair_4000D_Airflow {
            get {
                object obj = ResourceManager.GetObject("case_Corsair_4000D_Airflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Corsair_iCUE_500X_RGB {
            get {
                object obj = ResourceManager.GetObject("case_Corsair_iCUE_500X_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Fractal_Design_Define_7 {
            get {
                object obj = ResourceManager.GetObject("case_Fractal_Design_Define_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Fractal_Design_Meshify_C {
            get {
                object obj = ResourceManager.GetObject("case_Fractal_Design_Meshify_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Lian_Li_Lancool_215 {
            get {
                object obj = ResourceManager.GetObject("case_Lian_Li_Lancool_215", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Lian_Li_O11_Dynamic {
            get {
                object obj = ResourceManager.GetObject("case_Lian_Li_O11_Dynamic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MasterBox_NR200P_SE {
            get {
                object obj = ResourceManager.GetObject("case_MasterBox_NR200P_SE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MSI_MPG_Sekira_500X {
            get {
                object obj = ResourceManager.GetObject("case_MSI_MPG_Sekira_500X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MSI_MPG_Velox_100 {
            get {
                object obj = ResourceManager.GetObject("case_MSI_MPG_Velox_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_NZXT_H510 {
            get {
                object obj = ResourceManager.GetObject("case_NZXT_H510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_NZXT_H710i {
            get {
                object obj = ResourceManager.GetObject("case_NZXT_H710i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Phanteks_Eclipse_G360A {
            get {
                object obj = ResourceManager.GetObject("case_Phanteks_Eclipse_G360A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Phanteks_Eclipse_P400A {
            get {
                object obj = ResourceManager.GetObject("case_Phanteks_Eclipse_P400A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Thermaltake_H500 {
            get {
                object obj = ResourceManager.GetObject("case_Thermaltake_H500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Thermaltake_S100_TG {
            get {
                object obj = ResourceManager.GetObject("case_Thermaltake_S100_TG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_3_3200G {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_3_3200G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_3_3300X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_3_3300X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_5_5600X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_5_5600X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_5800X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_5800X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_7700X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_7700X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_7800X3D {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_7800X3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_5900X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_5900X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_5950X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_5950X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_7900X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_7900X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_7900X3D {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_7900X3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i3_10100 {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i3_10100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_11600K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_11600K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_12400 {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_12400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_12600K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_12600K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i7_11700K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i7_11700K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i7_12700K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i7_12700K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_10900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_10900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_11900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_11900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_12900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_12900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_14900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_14900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EVGA_GeForce_RTX_2080_Super {
            get {
                object obj = ResourceManager.GetObject("EVGA_GeForce_RTX_2080_Super", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1070 {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1080_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1080_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1660_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1660_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_RTX_2070_Super {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_RTX_2070_Super", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_RTX_3080_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_RTX_3080_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Arc_A770 {
            get {
                object obj = ResourceManager.GetObject("Intel_Arc_A770", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B450M_Steel_Legend {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B450M_Steel_Legend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B460M_Pro4 {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B460M_Pro4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B550_Phantom_Gaming_4 {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B550_Phantom_Gaming_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_Z690_Extreme {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_Z690_Extreme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_Prime_B460M_A {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_Prime_B460M_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_B550_F_Gaming_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_B550_F_Gaming_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_X570_E_Gaming {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_X570_E_Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_X570_I_Gaming_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_X570_I_Gaming_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_EVGA_X570_Dark {
            get {
                object obj = ResourceManager.GetObject("mb_EVGA_X570_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B450M_DS3H_WIFI {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B450M_DS3H_WIFI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B460M_DS3H {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B460M_DS3H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B550M_Aorus_Pro {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B550M_Aorus_Pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_Z490_Aorus_Elite {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_Z490_Aorus_Elite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B460M_Bazooka_V2 {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B460M_Bazooka_V2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B460M_Mortar_Micro_ATX_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B460M_Mortar_Micro_ATX_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B550M_Mortar_Micro_ATX {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B550M_Mortar_Micro_ATX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B560M_Mortar_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B560M_Mortar_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MEG_Z690_Godlike {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MEG_Z690_Godlike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MPG_X570_Gaming_Plus {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MPG_X570_Gaming_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MPG_Z490_Gaming_Carbon_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MPG_Z490_Gaming_Carbon_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Acer_Predator_XB323QK_NV {
            get {
                object obj = ResourceManager.GetObject("mon_Acer_Predator_XB323QK_NV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_AOC_Agon_AG352UCG6 {
            get {
                object obj = ResourceManager.GetObject("mon_AOC_Agon_AG352UCG6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_AOC_CQ32G1S {
            get {
                object obj = ResourceManager.GetObject("mon_AOC_CQ32G1S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Apple_Pro_Display_XDR {
            get {
                object obj = ResourceManager.GetObject("mon_Apple_Pro_Display_XDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Asus_ProArt_Display_PA32UCG {
            get {
                object obj = ResourceManager.GetObject("mon_Asus_ProArt_Display_PA32UCG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Asus_ROG_Strix_XG43UQ {
            get {
                object obj = ResourceManager.GetObject("mon_Asus_ROG_Strix_XG43UQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_BenQ_PD3220U {
            get {
                object obj = ResourceManager.GetObject("mon_BenQ_PD3220U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Dell_UltraSharp_U3223QE {
            get {
                object obj = ResourceManager.GetObject("mon_Dell_UltraSharp_U3223QE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Gigabyte_M32U {
            get {
                object obj = ResourceManager.GetObject("mon_Gigabyte_M32U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_HP_Z34C_G3 {
            get {
                object obj = ResourceManager.GetObject("mon_HP_Z34C_G3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_iiyama_G_Master_GB3466WQSU_B1 {
            get {
                object obj = ResourceManager.GetObject("mon_iiyama_G_Master_GB3466WQSU_B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Lenovo_ThinkVision_P34w_20 {
            get {
                object obj = ResourceManager.GetObject("mon_Lenovo_ThinkVision_P34w_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_LG_27GP950_B {
            get {
                object obj = ResourceManager.GetObject("mon_LG_27GP950_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_LG_UltraFine_Ergo_32EP950_B {
            get {
                object obj = ResourceManager.GetObject("mon_LG_UltraFine_Ergo_32EP950_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_MSI_MEG_341CQR {
            get {
                object obj = ResourceManager.GetObject("mon_MSI_MEG_341CQR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_MSI_Modern_AM271CQP_Monitor {
            get {
                object obj = ResourceManager.GetObject("mon_MSI_Modern_AM271CQP_Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Philips_Evnia_34M2C7600MV {
            get {
                object obj = ResourceManager.GetObject("mon_Philips_Evnia_34M2C7600MV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Samsung_Odyssey_G9 {
            get {
                object obj = ResourceManager.GetObject("mon_Samsung_Odyssey_G9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Samsung_Odyssey_Neo_G8 {
            get {
                object obj = ResourceManager.GetObject("mon_Samsung_Odyssey_Neo_G8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_ViewSonic_Elite_XG270QG {
            get {
                object obj = ResourceManager.GetObject("mon_ViewSonic_Elite_XG270QG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_GeForce_RTX_3070 {
            get {
                object obj = ResourceManager.GetObject("MSI_GeForce_RTX_3070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nvidia_GeForce_RTX_3060_Ti_Founders_Edition {
            get {
                object obj = ResourceManager.GetObject("Nvidia_GeForce_RTX_3060_Ti_Founders_Edition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nvidia_GeForce_RTX_4080_Founders_Edition {
            get {
                object obj = ResourceManager.GetObject("Nvidia_GeForce_RTX_4080_Founders_Edition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Radeon_RX_580 {
            get {
                object obj = ResourceManager.GetObject("PowerColor_Radeon_RX_580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Radeon_RX_6800_XT {
            get {
                object obj = ResourceManager.GetObject("PowerColor_Radeon_RX_6800_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Asus_ROG_Thor_1200W_Platinum {
            get {
                object obj = ResourceManager.GetObject("psu_Asus_ROG_Thor_1200W_Platinum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Asus_TUF_Gaming_750W_Bronze {
            get {
                object obj = ResourceManager.GetObject("psu_Asus_TUF_Gaming_750W_Bronze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_be_quiet__Pure_Power_10_CM_850W {
            get {
                object obj = ResourceManager.GetObject("psu_be_quiet__Pure_Power_10_CM_850W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Cooler_Master_MasterWatt_Maker_1200_Titanium {
            get {
                object obj = ResourceManager.GetObject("psu_Cooler_Master_MasterWatt_Maker_1200_Titanium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Cooler_Master_MWE_Bronze_V650 {
            get {
                object obj = ResourceManager.GetObject("psu_Cooler_Master_MWE_Bronze_V650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_AX1500i {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_AX1500i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_CX450M {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_CX450M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_RM1000x {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_RM1000x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_B550_Bronze {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_B550_Bronze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_G__1000W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_G__1000W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_SuperNOVA_1600_T2 {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_SuperNOVA_1600_T2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Gigabyte_P850W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_Gigabyte_P850W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_MSI_MPG_A_GF_AI_850W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_MSI_MPG_A_GF_AI_850W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_NZXT_C850_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_NZXT_C850_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_Prime_PX_1000 {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_Prime_PX_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_PRIME_TX_1600_Titanium {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_PRIME_TX_1600_Titanium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_S12III_Bronze_550W {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_S12III_Bronze_550W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Super_Flower_Leadex_III_Gold_750W {
            get {
                object obj = ResourceManager.GetObject("psu_Super_Flower_Leadex_III_Gold_750W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Thermaltake_Smart_650W {
            get {
                object obj = ResourceManager.GetObject("psu_Thermaltake_Smart_650W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Thermaltake_Toughpower_Grand_RGB_1200W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_Thermaltake_Toughpower_Grand_RGB_1200W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Aegis_F4_Series {
            get {
                object obj = ResourceManager.GetObject("ram_Aegis_F4_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ballistix_MAX_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Ballistix_MAX_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ballistix_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_Ballistix_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Dominator_Platinum_32GB_DDR5_5200 {
            get {
                object obj = ResourceManager.GetObject("ram_Dominator_Platinum_32GB_DDR5_5200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Fury_Beast_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_Fury_Beast_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Fury_Beast_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Fury_Beast_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_FURY_Renegade_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_FURY_Renegade_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Gammix_D10 {
            get {
                object obj = ResourceManager.GetObject("ram_Gammix_D10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ripjaws_S5_Series_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Ripjaws_S5_Series_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ripjaws_V_Series {
            get {
                object obj = ResourceManager.GetObject("ram_Ripjaws_V_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Dark_Z_Alpha_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Dark_Z_Alpha_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Delta_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Delta_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Delta_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Delta_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Vulcan_Z {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Vulcan_Z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_TridentZ_RGB_Series {
            get {
                object obj = ResourceManager.GetObject("ram_TridentZ_RGB_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_TridentZ5_RGB_Series {
            get {
                object obj = ResourceManager.GetObject("ram_TridentZ5_RGB_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Vengeance_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Vengeance_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Vengeance_RGB_PRO {
            get {
                object obj = ResourceManager.GetObject("ram_Vengeance_RGB_PRO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Viper_Steel_Series_DDR4 {
            get {
                object obj = ResourceManager.GetObject("ram_Viper_Steel_Series_DDR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_XPG_Lancer_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_XPG_Lancer_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sapphire_NITRO__Radeon_RX_6600_XT {
            get {
                object obj = ResourceManager.GetObject("Sapphire_NITRO+_Radeon_RX_6600_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sapphire_PULSE_Radeon_RX_570_8G_G5 {
            get {
                object obj = ResourceManager.GetObject("Sapphire_PULSE_Radeon_RX_570_8G_G5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_Radeon_RX_5700_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_Radeon_RX_5700_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_Radeon_RX_6700_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_Radeon_RX_6700_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_RX_5600_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_RX_5600_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
