//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Building_Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC_Building_Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASRock_AMD_Radeon_RX_6600_Challenger_D_8GB {
            get {
                object obj = ResourceManager.GetObject("ASRock_AMD_Radeon_RX_6600_Challenger_D_8GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Asus_ROG_Strix_GeForce_GTX_1060 {
            get {
                object obj = ResourceManager.GetObject("Asus_ROG_Strix_GeForce_GTX_1060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_TUF_Gaming_RX_7800_XT {
            get {
                object obj = ResourceManager.GetObject("ASUS_TUF_Gaming_RX_7800_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_ASUS_ROG_Strix_Helios {
            get {
                object obj = ResourceManager.GetObject("case_ASUS_ROG_Strix_Helios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_be_quiet__Pure_Base_500DX {
            get {
                object obj = ResourceManager.GetObject("case_be_quiet__Pure_Base_500DX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_be_quiet__Silent_Base_802 {
            get {
                object obj = ResourceManager.GetObject("case_be_quiet__Silent_Base_802", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Cooler_Master_MasterBox_NR200P {
            get {
                object obj = ResourceManager.GetObject("case_Cooler_Master_MasterBox_NR200P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Cooler_Master_MasterCase_H500M {
            get {
                object obj = ResourceManager.GetObject("case_Cooler_Master_MasterCase_H500M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Corsair_4000D_Airflow {
            get {
                object obj = ResourceManager.GetObject("case_Corsair_4000D_Airflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Corsair_iCUE_500X_RGB {
            get {
                object obj = ResourceManager.GetObject("case_Corsair_iCUE_500X_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Fractal_Design_Define_7 {
            get {
                object obj = ResourceManager.GetObject("case_Fractal_Design_Define_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Fractal_Design_Meshify_C {
            get {
                object obj = ResourceManager.GetObject("case_Fractal_Design_Meshify_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Lian_Li_Lancool_215 {
            get {
                object obj = ResourceManager.GetObject("case_Lian_Li_Lancool_215", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Lian_Li_O11_Dynamic {
            get {
                object obj = ResourceManager.GetObject("case_Lian_Li_O11_Dynamic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MasterBox_NR200P_SE {
            get {
                object obj = ResourceManager.GetObject("case_MasterBox_NR200P_SE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MSI_MPG_Sekira_500X {
            get {
                object obj = ResourceManager.GetObject("case_MSI_MPG_Sekira_500X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_MSI_MPG_Velox_100 {
            get {
                object obj = ResourceManager.GetObject("case_MSI_MPG_Velox_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_NZXT_H510 {
            get {
                object obj = ResourceManager.GetObject("case_NZXT_H510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_NZXT_H710i {
            get {
                object obj = ResourceManager.GetObject("case_NZXT_H710i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Phanteks_Eclipse_G360A {
            get {
                object obj = ResourceManager.GetObject("case_Phanteks_Eclipse_G360A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Phanteks_Eclipse_P400A {
            get {
                object obj = ResourceManager.GetObject("case_Phanteks_Eclipse_P400A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Thermaltake_H500 {
            get {
                object obj = ResourceManager.GetObject("case_Thermaltake_H500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap case_Thermaltake_S100_TG {
            get {
                object obj = ResourceManager.GetObject("case_Thermaltake_S100_TG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_3_3200G {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_3_3200G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_3_3300X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_3_3300X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_5_5600X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_5_5600X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_5800X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_5800X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_7700X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_7700X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_7_7800X3D {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_7_7800X3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_5900X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_5900X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_5950X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_5950X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_7900X {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_7900X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_AMD_Ryzen_9_7900X3D {
            get {
                object obj = ResourceManager.GetObject("cpu_AMD_Ryzen_9_7900X3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i3_10100 {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i3_10100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_11600K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_11600K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_12400 {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_12400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i5_12600K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i5_12600K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i7_11700K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i7_11700K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i7_12700K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i7_12700K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_10900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_10900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_11900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_11900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_12900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_12900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpu_Intel_Core_i9_14900K {
            get {
                object obj = ResourceManager.GetObject("cpu_Intel_Core_i9_14900K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EVGA_GeForce_RTX_2080_Super {
            get {
                object obj = ResourceManager.GetObject("EVGA_GeForce_RTX_2080_Super", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1070 {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1080_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1080_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_GTX_1660_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_GTX_1660_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_RTX_2070_Super {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_RTX_2070_Super", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gigabyte_GeForce_RTX_3080_Ti {
            get {
                object obj = ResourceManager.GetObject("Gigabyte_GeForce_RTX_3080_Ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_HGST_Deskstar_NAS_4TB {
            get {
                object obj = ResourceManager.GetObject("hdd_HGST_Deskstar_NAS_4TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_HGST_Ultrastar_12TB {
            get {
                object obj = ResourceManager.GetObject("hdd_HGST_Ultrastar_12TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Hitachi_Deskstar_500GB {
            get {
                object obj = ResourceManager.GetObject("hdd_Hitachi_Deskstar_500GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Hitachi_Ultrastar_5TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Hitachi_Ultrastar_5TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Samsung_Spinpoint_1TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Samsung_Spinpoint_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_Barracuda_3TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_Barracuda_3TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_BarraCuda_Pro_14TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_BarraCuda_Pro_14TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_Constellation_3TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_Constellation_3TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_FireCuda_8TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_FireCuda_8TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_IronWolf_10TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_IronWolf_10TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Seagate_SkyHawk_14TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Seagate_SkyHawk_14TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Toshiba_DT01ACA_1TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Toshiba_DT01ACA_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Toshiba_N300_14TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Toshiba_N300_14TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Toshiba_P300_3TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Toshiba_P300_3TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Toshiba_X300_6TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Toshiba_X300_6TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_WD_VelociRaptor_1TB {
            get {
                object obj = ResourceManager.GetObject("hdd_WD_VelociRaptor_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Western_Digital_Black_2_5TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Western_Digital_Black_2_5TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Western_Digital_Blue_2TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Western_Digital_Blue_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Western_Digital_Gold_18TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Western_Digital_Gold_18TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hdd_Western_Digital_Red_8TB {
            get {
                object obj = ResourceManager.GetObject("hdd_Western_Digital_Red_8TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Arc_A770 {
            get {
                object obj = ResourceManager.GetObject("Intel_Arc_A770", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Anne_Pro_2 {
            get {
                object obj = ResourceManager.GetObject("key_Anne_Pro_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Apple_Magic_Keyboard {
            get {
                object obj = ResourceManager.GetObject("key_Apple_Magic_Keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Asus_ROG_Strix_Scope_TKL {
            get {
                object obj = ResourceManager.GetObject("key_Asus_ROG_Strix_Scope_TKL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Cooler_Master_SK622 {
            get {
                object obj = ResourceManager.GetObject("key_Cooler_Master_SK622", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_CORSAIR_K100_RGB {
            get {
                object obj = ResourceManager.GetObject("key_CORSAIR_K100_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Ducky_One_3_Mini {
            get {
                object obj = ResourceManager.GetObject("key_Ducky_One_3_Mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Epomaker_GK68XS {
            get {
                object obj = ResourceManager.GetObject("key_Epomaker_GK68XS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Fnatic_STREAK65_LP {
            get {
                object obj = ResourceManager.GetObject("key_Fnatic_STREAK65_LP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Glorious_GMMK_Pro {
            get {
                object obj = ResourceManager.GetObject("key_Glorious_GMMK_Pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_HyperX_Alloy_Origins_Core {
            get {
                object obj = ResourceManager.GetObject("key_HyperX_Alloy_Origins_Core", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Keychron_Q1 {
            get {
                object obj = ResourceManager.GetObject("key_Keychron_Q1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Leopold_FC980M_PD {
            get {
                object obj = ResourceManager.GetObject("key_Leopold_FC980M_PD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Logitech_G915_TKL {
            get {
                object obj = ResourceManager.GetObject("key_Logitech_G915_TKL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Logitech_MX_Mechanical_Mini {
            get {
                object obj = ResourceManager.GetObject("key_Logitech_MX_Mechanical_Mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_MSI_Vigor_GK71 {
            get {
                object obj = ResourceManager.GetObject("key_MSI_Vigor_GK71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Niz_Plum_82 {
            get {
                object obj = ResourceManager.GetObject("key_Niz_Plum_82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_NuPhy_Air75 {
            get {
                object obj = ResourceManager.GetObject("key_NuPhy_Air75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Razer_Blackwidow_V3_Pro {
            get {
                object obj = ResourceManager.GetObject("key_Razer_Blackwidow_V3_Pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_Redragon_K552 {
            get {
                object obj = ResourceManager.GetObject("key_Redragon_K552", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_SteelSeries_Apex_Pro_TKL {
            get {
                object obj = ResourceManager.GetObject("key_SteelSeries_Apex_Pro_TKL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B450M_Steel_Legend {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B450M_Steel_Legend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B460M_Pro4 {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B460M_Pro4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_B550_Phantom_Gaming_4 {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_B550_Phantom_Gaming_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASRock_Z690_Extreme {
            get {
                object obj = ResourceManager.GetObject("mb_ASRock_Z690_Extreme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_Prime_B460M_A {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_Prime_B460M_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_B550_F_Gaming_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_B550_F_Gaming_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_X570_E_Gaming {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_X570_E_Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_ASUS_ROG_Strix_X570_I_Gaming_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_ASUS_ROG_Strix_X570_I_Gaming_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_EVGA_X570_Dark {
            get {
                object obj = ResourceManager.GetObject("mb_EVGA_X570_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B450M_DS3H_WIFI {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B450M_DS3H_WIFI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B460M_DS3H {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B460M_DS3H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_B550M_Aorus_Pro {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_B550M_Aorus_Pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_Gigabyte_Z490_Aorus_Elite {
            get {
                object obj = ResourceManager.GetObject("mb_Gigabyte_Z490_Aorus_Elite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B460M_Bazooka_V2 {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B460M_Bazooka_V2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B460M_Mortar_Micro_ATX_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B460M_Mortar_Micro_ATX_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B550M_Mortar_Micro_ATX {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B550M_Mortar_Micro_ATX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_B560M_Mortar_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_B560M_Mortar_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MEG_Z690_Godlike {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MEG_Z690_Godlike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MPG_X570_Gaming_Plus {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MPG_X570_Gaming_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mb_MSI_MPG_Z490_Gaming_Carbon_WiFi {
            get {
                object obj = ResourceManager.GetObject("mb_MSI_MPG_Z490_Gaming_Carbon_WiFi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Acer_Predator_XB323QK_NV {
            get {
                object obj = ResourceManager.GetObject("mon_Acer_Predator_XB323QK_NV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_AOC_Agon_AG352UCG6 {
            get {
                object obj = ResourceManager.GetObject("mon_AOC_Agon_AG352UCG6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_AOC_CQ32G1S {
            get {
                object obj = ResourceManager.GetObject("mon_AOC_CQ32G1S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Apple_Pro_Display_XDR {
            get {
                object obj = ResourceManager.GetObject("mon_Apple_Pro_Display_XDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Asus_ProArt_Display_PA32UCG {
            get {
                object obj = ResourceManager.GetObject("mon_Asus_ProArt_Display_PA32UCG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Asus_ROG_Strix_XG43UQ {
            get {
                object obj = ResourceManager.GetObject("mon_Asus_ROG_Strix_XG43UQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_BenQ_PD3220U {
            get {
                object obj = ResourceManager.GetObject("mon_BenQ_PD3220U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Dell_UltraSharp_U3223QE {
            get {
                object obj = ResourceManager.GetObject("mon_Dell_UltraSharp_U3223QE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Gigabyte_M32U {
            get {
                object obj = ResourceManager.GetObject("mon_Gigabyte_M32U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_HP_Z34C_G3 {
            get {
                object obj = ResourceManager.GetObject("mon_HP_Z34C_G3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_iiyama_G_Master_GB3466WQSU_B1 {
            get {
                object obj = ResourceManager.GetObject("mon_iiyama_G_Master_GB3466WQSU_B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Lenovo_ThinkVision_P34w_20 {
            get {
                object obj = ResourceManager.GetObject("mon_Lenovo_ThinkVision_P34w_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_LG_27GP950_B {
            get {
                object obj = ResourceManager.GetObject("mon_LG_27GP950_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_LG_UltraFine_Ergo_32EP950_B {
            get {
                object obj = ResourceManager.GetObject("mon_LG_UltraFine_Ergo_32EP950_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_MSI_MEG_341CQR {
            get {
                object obj = ResourceManager.GetObject("mon_MSI_MEG_341CQR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_MSI_Modern_AM271CQP_Monitor {
            get {
                object obj = ResourceManager.GetObject("mon_MSI_Modern_AM271CQP_Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Philips_Evnia_34M2C7600MV {
            get {
                object obj = ResourceManager.GetObject("mon_Philips_Evnia_34M2C7600MV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Samsung_Odyssey_G9 {
            get {
                object obj = ResourceManager.GetObject("mon_Samsung_Odyssey_G9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_Samsung_Odyssey_Neo_G8 {
            get {
                object obj = ResourceManager.GetObject("mon_Samsung_Odyssey_Neo_G8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_ViewSonic_Elite_XG270QG {
            get {
                object obj = ResourceManager.GetObject("mon_ViewSonic_Elite_XG270QG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Apple_Magic_Mouse_2 {
            get {
                object obj = ResourceManager.GetObject("mou_Apple_Magic_Mouse_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Corsair_Dark_Core_Pro_RGB_SE {
            get {
                object obj = ResourceManager.GetObject("mou_Corsair_Dark_Core_Pro_RGB_SE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Ducky_Feather {
            get {
                object obj = ResourceManager.GetObject("mou_Ducky_Feather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Fnatic_Flick_2 {
            get {
                object obj = ResourceManager.GetObject("mou_Fnatic_Flick_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Glorious_Model_D_Wireless {
            get {
                object obj = ResourceManager.GetObject("mou_Glorious_Model_D_Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Glorious_Model_O {
            get {
                object obj = ResourceManager.GetObject("mou_Glorious_Model_O", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_HyperX_Pulsefire_Haste {
            get {
                object obj = ResourceManager.GetObject("mou_HyperX_Pulsefire_Haste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_G_Pro_Wireless {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_G_Pro_Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_G305_Lightspeed {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_G305_Lightspeed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_G502_Hero {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_G502_Hero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_M220_Silent {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_M220_Silent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_MX_Anywhere_3 {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_MX_Anywhere_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_MX_Master_3 {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_MX_Master_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Logitech_MX_Vertical_Ergonomic_Mouse {
            get {
                object obj = ResourceManager.GetObject("mou_Logitech_MX_Vertical_Ergonomic_Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Razer_Basilisk_V3 {
            get {
                object obj = ResourceManager.GetObject("mou_Razer_Basilisk_V3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Razer_DeathAdder_V2_Mini {
            get {
                object obj = ResourceManager.GetObject("mou_Razer_DeathAdder_V2_Mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Razer_Naga_Trinity {
            get {
                object obj = ResourceManager.GetObject("mou_Razer_Naga_Trinity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_SteelSeries_Rival_650_Wireless {
            get {
                object obj = ResourceManager.GetObject("mou_SteelSeries_Rival_650_Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_SteelSeries_Rival_710 {
            get {
                object obj = ResourceManager.GetObject("mou_SteelSeries_Rival_710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mou_Zowie_S2_C_Divina_Series {
            get {
                object obj = ResourceManager.GetObject("mou_Zowie_S2_C_Divina_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_GeForce_RTX_3070 {
            get {
                object obj = ResourceManager.GetObject("MSI_GeForce_RTX_3070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nvidia_GeForce_RTX_3060_Ti_Founders_Edition {
            get {
                object obj = ResourceManager.GetObject("Nvidia_GeForce_RTX_3060_Ti_Founders_Edition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nvidia_GeForce_RTX_4080_Founders_Edition {
            get {
                object obj = ResourceManager.GetObject("Nvidia_GeForce_RTX_4080_Founders_Edition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Radeon_RX_580 {
            get {
                object obj = ResourceManager.GetObject("PowerColor_Radeon_RX_580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Radeon_RX_6800_XT {
            get {
                object obj = ResourceManager.GetObject("PowerColor_Radeon_RX_6800_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Asus_ROG_Thor_1200W_Platinum {
            get {
                object obj = ResourceManager.GetObject("psu_Asus_ROG_Thor_1200W_Platinum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Asus_TUF_Gaming_750W_Bronze {
            get {
                object obj = ResourceManager.GetObject("psu_Asus_TUF_Gaming_750W_Bronze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_be_quiet__Pure_Power_10_CM_850W {
            get {
                object obj = ResourceManager.GetObject("psu_be_quiet__Pure_Power_10_CM_850W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Cooler_Master_MasterWatt_Maker_1200_Titanium {
            get {
                object obj = ResourceManager.GetObject("psu_Cooler_Master_MasterWatt_Maker_1200_Titanium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Cooler_Master_MWE_Bronze_V650 {
            get {
                object obj = ResourceManager.GetObject("psu_Cooler_Master_MWE_Bronze_V650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_AX1500i {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_AX1500i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_CX450M {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_CX450M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Corsair_RM1000x {
            get {
                object obj = ResourceManager.GetObject("psu_Corsair_RM1000x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_B550_Bronze {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_B550_Bronze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_G__1000W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_G+_1000W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_EVGA_SuperNOVA_1600_T2 {
            get {
                object obj = ResourceManager.GetObject("psu_EVGA_SuperNOVA_1600_T2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Gigabyte_P850W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_Gigabyte_P850W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_MSI_MPG_A_GF_AI_850W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_MSI_MPG_A_GF_AI_850W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_NZXT_C850_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_NZXT_C850_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_Prime_PX_1000 {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_Prime_PX_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_PRIME_TX_1600_Titanium {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_PRIME_TX_1600_Titanium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Seasonic_S12III_Bronze_550W {
            get {
                object obj = ResourceManager.GetObject("psu_Seasonic_S12III_Bronze_550W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Super_Flower_Leadex_III_Gold_750W {
            get {
                object obj = ResourceManager.GetObject("psu_Super_Flower_Leadex_III_Gold_750W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Thermaltake_Smart_650W {
            get {
                object obj = ResourceManager.GetObject("psu_Thermaltake_Smart_650W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psu_Thermaltake_Toughpower_Grand_RGB_1200W_Gold {
            get {
                object obj = ResourceManager.GetObject("psu_Thermaltake_Toughpower_Grand_RGB_1200W_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Aegis_F4_Series {
            get {
                object obj = ResourceManager.GetObject("ram_Aegis_F4_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ballistix_MAX_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Ballistix_MAX_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ballistix_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_Ballistix_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Dominator_Platinum_32GB_DDR5_5200 {
            get {
                object obj = ResourceManager.GetObject("ram_Dominator_Platinum_32GB_DDR5_5200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Fury_Beast_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_Fury_Beast_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Fury_Beast_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Fury_Beast_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_FURY_Renegade_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_FURY_Renegade_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Gammix_D10 {
            get {
                object obj = ResourceManager.GetObject("ram_Gammix_D10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ripjaws_S5_Series_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Ripjaws_S5_Series_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Ripjaws_V_Series {
            get {
                object obj = ResourceManager.GetObject("ram_Ripjaws_V_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Dark_Z_Alpha_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Dark_Z_Alpha_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Delta_RGB {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Delta_RGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Delta_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Delta_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_T_Force_Vulcan_Z {
            get {
                object obj = ResourceManager.GetObject("ram_T_Force_Vulcan_Z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_TridentZ_RGB_Series {
            get {
                object obj = ResourceManager.GetObject("ram_TridentZ_RGB_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_TridentZ5_RGB_Series {
            get {
                object obj = ResourceManager.GetObject("ram_TridentZ5_RGB_Series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Vengeance_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_Vengeance_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Vengeance_RGB_PRO {
            get {
                object obj = ResourceManager.GetObject("ram_Vengeance_RGB_PRO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_Viper_Steel_Series_DDR4 {
            get {
                object obj = ResourceManager.GetObject("ram_Viper_Steel_Series_DDR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ram_XPG_Lancer_RGB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("ram_XPG_Lancer_RGB_DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sapphire_NITRO__Radeon_RX_6600_XT {
            get {
                object obj = ResourceManager.GetObject("Sapphire_NITRO+_Radeon_RX_6600_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sapphire_PULSE_Radeon_RX_570_8G_G5 {
            get {
                object obj = ResourceManager.GetObject("Sapphire_PULSE_Radeon_RX_570_8G_G5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Audioengine_A2__Wireless {
            get {
                object obj = ResourceManager.GetObject("spe_Audioengine_A2__Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Audioengine_A5__Wireless {
            get {
                object obj = ResourceManager.GetObject("spe_Audioengine_A5__Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Audioengine_HD3 {
            get {
                object obj = ResourceManager.GetObject("spe_Audioengine_HD3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Bose_Companion_20 {
            get {
                object obj = ResourceManager.GetObject("spe_Bose_Companion_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Creative_Pebble_Plus_2_0 {
            get {
                object obj = ResourceManager.GetObject("spe_Creative_Pebble_Plus_2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Edifier_R1280T {
            get {
                object obj = ResourceManager.GetObject("spe_Edifier_R1280T", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Edifier_S350DB {
            get {
                object obj = ResourceManager.GetObject("spe_Edifier_S350DB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_IK_Multimedia_iLoud_Micro_Monitor {
            get {
                object obj = ResourceManager.GetObject("spe_IK_Multimedia_iLoud_Micro_Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_JBL_Studio_530 {
            get {
                object obj = ResourceManager.GetObject("spe_JBL_Studio_530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Kali_Audio_LP_6 {
            get {
                object obj = ResourceManager.GetObject("spe_Kali_Audio_LP_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Kanto_YU4 {
            get {
                object obj = ResourceManager.GetObject("spe_Kanto_YU4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Klipsch_R_41M {
            get {
                object obj = ResourceManager.GetObject("spe_Klipsch_R_41M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Logitech_G560_LIGHTSYNC {
            get {
                object obj = ResourceManager.GetObject("spe_Logitech_G560_LIGHTSYNC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Mackie_CR3_XBT {
            get {
                object obj = ResourceManager.GetObject("spe_Mackie_CR3_XBT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Micca_RB42 {
            get {
                object obj = ResourceManager.GetObject("spe_Micca_RB42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Monoprice_DT_3BT {
            get {
                object obj = ResourceManager.GetObject("spe_Monoprice_DT_3BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Neumi_BS5 {
            get {
                object obj = ResourceManager.GetObject("spe_Neumi_BS5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_PreSonus_Eris_E3_5 {
            get {
                object obj = ResourceManager.GetObject("spe_PreSonus_Eris_E3_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Razer_Nommo_Chroma {
            get {
                object obj = ResourceManager.GetObject("spe_Razer_Nommo_Chroma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spe_Swan_M10_Plus {
            get {
                object obj = ResourceManager.GetObject("spe_Swan_M10_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_ADATA_SU800_SSD_256GB {
            get {
                object obj = ResourceManager.GetObject("ssd_ADATA_SU800_SSD_256GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Crucial_MX500_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Crucial_MX500_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Gigabyte_UD_PRO_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Gigabyte_UD_PRO_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_HP_S700_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_HP_S700_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Intel_545s_SSD_512GB {
            get {
                object obj = ResourceManager.GetObject("ssd_Intel_545s_SSD_512GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Kingston_A400_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Kingston_A400_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Kingston_UV500_SSD_512GB {
            get {
                object obj = ResourceManager.GetObject("ssd_Kingston_UV500_SSD_512GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Mushkin_Source_SSD_500GB {
            get {
                object obj = ResourceManager.GetObject("ssd_Mushkin_Source_SSD_500GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_OWC_Mercury_Electra_6G_SSD_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_OWC_Mercury_Electra_6G_SSD_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Patriot_Burst_SSD_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Patriot_Burst_SSD_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_PNY_CS900_SSD_4TB {
            get {
                object obj = ResourceManager.GetObject("ssd_PNY_CS900_SSD_4TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Samsung_870_EVO_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Samsung_870_EVO_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_SanDisk_Ultra_3D_SSD_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_SanDisk_Ultra_3D_SSD_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Seagate_Barracuda_SSD_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Seagate_Barracuda_SSD_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Silicon_Power_Ace_A55_SSD_512GB {
            get {
                object obj = ResourceManager.GetObject("ssd_Silicon_Power_Ace_A55_SSD_512GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_SK_hynix_Gold_S31_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_SK_hynix_Gold_S31_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Team_Group_L5_3D_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Team_Group_L5_3D_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Toshiba_TR200_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Toshiba_TR200_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Transcend_SSD230S_SSD_2TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Transcend_SSD230S_SSD_2TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssd_Western_Digital_Blue_SSD_1TB {
            get {
                object obj = ResourceManager.GetObject("ssd_Western_Digital_Blue_SSD_1TB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_Radeon_RX_5700_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_Radeon_RX_5700_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_Radeon_RX_6700_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_Radeon_RX_6700_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XFX_RX_5600_XT {
            get {
                object obj = ResourceManager.GetObject("XFX_RX_5600_XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
